### ISSUE TITLE
need help with C++ debugging

### ISSUE THREAD

**Issue by R3D9477** [Gama11/HaxeRepro#1]
Hi. Which debugger you are using for c++ debugging?
With config from your repo I have exception: Debug adapter process has terminated unexpectedly.

Tested on:
```
Haxe 3.4.4
VSCode 1.7.17
VSCode Haxe 1.9.2
VSCode Haxe Debug 1.1.2
VSCode Haxe Extension Pack 1.0.0
vscode-hxcpp-debug from git
haxelib hxcpp 3.4.90
haxelib hxcpp-debugger from git
Linux Mint 18.2 x64
```

Also I have notification in launch.json: `Property program is not allowed`.

And here what options is allowed for hxcpp:
![321](https://user-images.githubusercontent.com/15020827/32171866-a4e14f94-bd8a-11e7-9d60-a51898736f49.png)

Thanks.

**Comment by Gama11** [comment]
You need to clone the `devel` branch of `vshaxe-debugadapter` and install from source (the debug adapter version that also supports C++ isn't on the marketplace yet):

https://github.com/vshaxe/vshaxe-debugadapter#installing-from-source

**Comment by R3D9477** [comment]
@Gama11 Thanks, with version from develop branch property "program" is allow now, but debugger still doesn't work. I have error message: `Debug adapter process has terminated unexpectedly `
![123](https://user-images.githubusercontent.com/15020827/32189104-cf537a56-bdba-11e7-8202-f333e4c20f8e.png)

Do you have a positive result of debugging via hxcpp?
Which version of nodejs, haxe and vscode do you using?

**Comment by Gama11** [comment]
I just tried and couldn't get breakpoints to trigger (not getting the error you have though, it's just stuck loading). Maybe something broke with a recent VSCode update, I haven't tried C++ debugging in a while...

**Comment by Gama11** [comment]
There's a new hxcpp debugger extension at https://github.com/vshaxe/hxcpp-debugger which works for me with latest VSCode. I also updated the launch config in this repo for it.

Should be published on the VSCode marketplace soon-ish.
